name       : python-pythondialog
version    : 3.5.1
release    : 1
source     :
    - https://files.pythonhosted.org/packages/72/3c/26ed0db035f97196704d0197d8b2254b8a6ca93a2d132430b0b0d597aa79/pythondialog-3.5.1.tar.gz : 34a0687290571f37d7d297514cc36bd4cd044a3a4355271549f91490d3e7ece8
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A Python interface to the UNIX dialog utility and mostly-compatible programs
description: |
    A Python interface to the UNIX dialog utility and mostly-compatible programs
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - dialog
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
