name       : python-pythondialog
version    : 3.5.2
release    : 3
source     :
    - https://pypi.io/packages/source/p/pythondialog/pythondialog-3.5.2.tar.gz : 4fc11e95540d1d5dbe0a60cd3fb7787354df85ee4b5da21f708ea46cb47bf6d6
license    : LGPL-2.1-or-later
component  : programming.python
summary    : A Python interface to the UNIX dialog utility and mostly-compatible programs
description: |
    A Python interface to the UNIX dialog utility and mostly-compatible programs
builddeps  :
    - pkgconfig(python3)
rundeps    :
    - dialog
    - python3
build      : |
    %python3_setup
install    : |
    %python3_install
